### PR TITLE
#377: Value entry is optional now

### PR DESCRIPTION
**Pull request by ilyamaier**
Just deleted the value's EditText and error message from the array.

### CODE REVIEW

**Comment by IlyaMaier** [comment]
Merging is blocked because of a json file:
ERROR: (gcloud.auth.activate-service-account) Could not read json file /home/circleci/gcloud-service-key.json: No JSON object could be decoded

**Comment by codeguru42** [comment]
Yes, my CI build is a little broken. It requires a Firebase key to run tests. Don't worry about it.

**Comment by IlyaMaier** [comment]
> Thank you for the PR. The edit text should remain, but allowed to be blank when the user saves. Also please maintain 4 space indents for continuation lines.

I returned 4 space indents. The edit text is remained, only the error message is deleted, so that it doesn't appear at check time.

**Comment by codeguru42** [comment]
I will finish my review later this week. I'm replying from my phone right now.

**Comment by codeguru42** [comment]
When I try to add a card with the Value field blank, I get an error:
>2019-10-08 17:22:44.716 12489-12489/bbct.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: bbct.android, PID: 12489
    java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at bbct.android.common.activity.BaseballCardDetails.getBaseballCard(BaseballCardDetails.java:326)
        at bbct.android.common.activity.BaseballCardDetails.onSave(BaseballCardDetails.java:352)
        at bbct.android.common.activity.BaseballCardDetails.onOptionsItemSelected(BaseballCardDetails.java:278)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2678)
        at androidx.fragment.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManagerImpl.java:2718)
        at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:412)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:377)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:197)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:889)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by codeguru42** [comment]
@IlyaMaier Just following up on this PR. This needs more work as I noted in my previous comment. Please also add a test that shows your change works.

**Comment by codeguru42** [comment]
@IlyaMaier Will you have time to work on this PR this weekend? I'd like to get this finish up and merged before the end of the month.

**Comment by IlyaMaier** [comment]
> @IlyaMaier Will you have time to work on this PR this weekend? I'd like to get this finish up and merged before the end of the month.

Yes! Sorry, I was a little bit busy with school work.

**Comment by codeguru42** [comment]
No need to apologize. I just want to keep in touch at least once a week to see how things are going.

**Pull request closed without merging**
